### ISSUE TITLE
Selected text unreadable due to styling

### ISSUE THREAD

**Issue by thakkarparth007** [vednoc/onyx#13]
Selected text has blue background and white foreground but the shades make it impossible to read the selected text. This needs to be fixed.

Everything else is great (: 

![jpeg image 766 x 82 pixels](https://user-images.githubusercontent.com/747423/48207451-aa814c00-e396-11e8-8af4-20b25d6d5572.jpg)

**Comment by vednoc** [comment]
Hi @thakkarparth007!

Which browser are you using? I see no issues on my end since the theme doesn't handle `::selection`/`::-moz-selection` selector and it's inherited from the browser's default stylesheet.

I might, probably should, apply custom styles to it. If so, tell me what you think about this. :smile:

![image](https://user-images.githubusercontent.com/18245694/48293551-fe1b9480-e47f-11e8-9bcb-ec834188c3c1.png)

**Comment by thakkarparth007** [comment]
Hey, this looks good, thanks!

I was using Mozilla btw, not sure why it was different for me. Maybe OS default?

Anyway, thanks for the update :)

**Comment by vednoc** [comment]
Thanks for reporting this issue and I'm glad you're enjoying the theme. :smiley:

>I was using Mozilla btw, not sure why it was different for me. Maybe OS default?

If you're using Linux then it's most likely caused by the global GTK theme. I couldn't find anything related to `::selection:` in the official WhatsApp CSS file, so that's my bet.
