### ISSUE TITLE
Suggestion: include message checks on compact view

### ISSUE THREAD

**Issue by igorsantos07** [vednoc/onyx#14]
It would be interesting to see, in a quick glance on the compact window, if someone received your message or not, without having to hover the chat list or opening their messages. This could come up as a configurable option if found bothersome for some people, but it seems that the longest part of the chat list are the messages, not the icons :)

It could work the same way as the unread messages counter, being left over the chat avatar.

**Comment by vednoc** [comment]
I've been meaning to improve the compact mode, so thanks a lot for this lovely suggestion! :blush:

Here is a little something I worked on and it looks quite good, I think. Another thought I had was to put the message status in the same place as the unread message counter since it disappears whenever you have unseen message(s).

As far as the configurable option goes, that could be a thing if someone really wants it -- I don't think anyone would dislike the way it looks in the attached screenshot.

![image](https://user-images.githubusercontent.com/18245694/48587418-5b598f00-e933-11e8-87a5-ef287eeff21c.png)

**Comment by vednoc** [comment]
Finally came back to this and kinda managed to hack it enough so that it works without being quite buggy but it's by no means a perfect implementation. Sorry for the long wait. :sweat_smile: :tada:
