### ISSUE TITLE
Broadcast icons are completely white unless on hover

### ISSUE THREAD

**Issue by igorsantos07** [vednoc/onyx#15]
I guess the gif and title are self-explanatory :)
![peek 2018-11-15 01-12](https://user-images.githubusercontent.com/532299/48527838-a7dd9580-e873-11e8-84a3-a577c64ee972.gif)

I couldn't easily find the fix for this, but it seems that, on hover at the span icon, it changes some color - couldn't discover where.

**Comment by vednoc** [comment]
It is self-explanatory but I've never seen that icon before! :scream: The reason why it changes the color is because of [this line](https://github.com/vednoc/onyx/blob/master/WhatsApp.user.css#L1123).

Could you tell me how to reproduce it or get the HTML snippet of the icon, including it's child and parent elements? It should start with something like this: `<span data-icon="icon-name">`

**Comment by igorsantos07** [comment]
It's a broadcast list :)

I'll get it for you by Monday or Tuesday, on holidays now haha 🏖

**Comment by igorsantos07** [comment]
Checking on my computer now. It seems it's not possible to create a broadcast list from Web. [Here's info on it and the how-to](https://faq.whatsapp.com/en/android/23130793/?category=5245251).

Here's the HTML snippet:
```html
<span data-icon="default-broadcast" class="">
    <svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 212 212" width="212" height="212"><path fill="#DFE5E7" d="M106.251.5C164.653.5 212 47.846 212 106.25S164.653 212 106.25 212C47.846 212 .5 164.654.5 106.25S47.846.5 106.251.5z"></path><path fill="#FFF" d="M152.168 54.014l-11.66 4.364v95.453l11.744 4.161-.084-103.978zM49.742 121.662l18.892 6.698c0 .14-.021.274-.021.414 0 14.507 11.782 26.269 26.318 26.269 8.39 0 15.849-3.935 20.669-10.039l18.328 6.495v-90.66L49.742 92.355v29.307zm58.56 20.755c-3.455 3.371-8.169 5.458-13.371 5.458-9.818 0-17.921-7.419-19.005-16.934l32.376 11.476z"></path></svg>
</span>
```
