### ISSUE TITLE
Contact photo not expanding when clicked

### ISSUE THREAD

**Issue by andremendesc** [vednoc/onyx#18]
The feature: In a conversation, you can click in a contact to invoke "Contact Info" view
Then you can click on the contact photo so it expands showing its full sized version.

The problem: After calling the "Contact Info" view and then clicking in the contact image. The expanded photo doesn't show up at all if you are using this theme.

######Tested on Firefox 63.0.3 (64-bit)

**Comment by vednoc** [comment]
Hi!

That is quite weird. I've tested it in a variety of browsers (various Chromium-based browsers, Waterfox 56, Firefox 60 ESR, Firefox 61 and Firefox 64) but the profile image always shows up as it should.

What's the current version of WhatsApp that you're running? You can check it in settings -> help menu on web.whatsapp.com. Other than that, try to load any image from media section since they use the same markup to check whether that works or not.

**Comment by andremendesc** [comment]
This is really weird because I just checked it again and it indeed worked as expected. I'm using WhatsApp version 0.3.1649. 
I haven't checked the version at the time of writing this issue so I don't know if it had any updates. Anyways I am sorry to waste your time. 
Kudos for your work on the themes! They're great.

**Comment by vednoc** [comment]
The version is the same as when the "stickers" update came out. Even I had some random glitches before when sending emojis, changing profile image or even opening the info/starred/archive panes.

No worries, I'm glad that this is sorted out. Thanks for the kind words! :blush:
