### ISSUE TITLE
Name and status of contact text colors are black -> unreadable

### ISSUE THREAD

**Issue by vpultoo** [vednoc/onyx#24]
The name and status of a contact in a conversation with the contact are unreadable because the text colors are black.

Quick fix is to add this to the code:

/* Name contact */

    .app ._3XrHh {
      color: var(--light); }

/* Status contact */

    .app ._3sgkv {
      color: var(--light); }

**Comment by vednoc** [comment]
Thanks for reporting this but it's already fixed in v1.3.0. You might have to force an update or reinstall onyx if you've modified the code locally since Stylus doesn't auto-update locally modified styles.

Also check out [v1.3.0](https://github.com/vednoc/onyx/releases/tag/1.3.0) changelog if you're interested in what's changed.
