### ISSUE TITLE
Some lasting bugs after June 7th update

### ISSUE THREAD

**Issue by Virkkunen** [vednoc/onyx#35]
1- On compact mode, there's no unread badge on the corner of the chat's image. It does show when hovering the chat list
https://i.imgur.com/HCljqDa.png
https://i.imgur.com/Tk4r7od.png

2- There's no animation when expanding the compact list, it's only compacted or expanded, also there's a long delay for the chat list to expand after hovering

3- Window proportions are a bit off. Before I could have a small square window (about the same size as the image), now the smaller size before the scrollbars appear is a larger rectangle. Also when sharing an image, the preview window is smaller than the chat window.
https://i.imgur.com/xiDyH5I.png
https://i.imgur.com/MuwXWG1.png

**Comment by vednoc** [comment]
I lack the time to re-implement and debug everything properly.

1) It'll probably be back but it'll be tricky. Last time it took me *too* long to get it right.

2) Long delay is there so it doesn't trigger constantly. It might become a customizable option. Animation is gone because it was causing glitches and I removed it temporarily.

3) I've seen it. Wasn't my priority since it's not used as much as main panes so I skipped it after spending a little bit of time because it ended up just causing a lot of trouble with other panes.
