### ISSUE TITLE
Message text input is white

### ISSUE THREAD

**Issue by simonsmith** [vednoc/onyx#4]
![screen shot 2018-07-31 at 18 40 03](https://user-images.githubusercontent.com/360703/43476723-2f2f6a12-94f1-11e8-98fb-58f0aa7410b2.png)

Emoji menu is partially affected too

Thanks!

**Comment by vednoc** [comment]
Do you have the latest version? Update the userstyle manually and check if the version is 1.0.10; you also might need to force an update if you edited the style locally since Stylus doesn't auto-update locally edited userstyles. Otherwise, if it's a new update I'll have to wait for it to land on my end.

**Comment by simonsmith** [comment]
The version in master (and on the 1.0.10 tag) is showing as 1.0.9 in the comment, I think that's what confused me. I've just forced a reinstall and that has fixed it.

**Comment by vednoc** [comment]
Oh, I forgot to update that line. Thanks for letting me know, glad you got it working now. :smile:
