### ISSUE TITLE
Text input field not affected by custom css

### ISSUE THREAD

**Issue by TheEbolaDoc** [vednoc/onyx#5]
Hey ! 
At first, let me thank you for the awesome whatsapp theme you have written :blush: :heart:  

In the current WhatsApp version the message input field, aswell as the bar you can fold out are currently broken.
For details see my screenshot [image](https://imgur.com/gallery/Vu6uMqK)

Keep up the good work!
Greetings
chris

**Comment by vednoc** [comment]
Thanks for the kind words. :smiley:

I've fixed these issues in the last few updates, make sure to either update the theme manually or reinstall it by clicking on the "Install directly with Stylus" button. The version is still 1.0.9 in the code because I forgot to change it, but there are 1121 lines in total. Let me know how it goes!

**Comment by vednoc** [comment]
Update: Turns out Stylus checks for `@version` and doesn't auto-update if they're the same, so this was purely my mistake. Sorry for the inconvenience, this shouldn't happen again in the future. :sweat_smile:
